Repository IT2901Nordic2024/backend, pull requests merged in 2024-04, with the labels that each got.

#45 [#42]refactor: Update firmwareSimulator and proto files
  firmwareSimulator/fromFirmwareToBackend_pb2.py
  firmwareSimulator/habitTracker.py
  firmwareSimulator/main.py
  firmwareSimulator/protocol_buffers_messages/fromFirmwareToBackend.desc
  firmwareSimulator/protocol_buffers_messages/fromFirmwareToBackend.proto
Labels: bug

#47 [#46]fix: Update the .desc file in protocolBuffersDescriptorFilesBucket
  firmwareSimulator/main.py
  habit-event-storage/proto-files/fromFirmwareToBackend.desc
  habit-event-storage/proto-files/fromFirmwareToBackend.proto
  habit-event-storage/proto-files/fromFirmwareToBackend.zip
Labels: bug

#54 51 feature create api for deleting habits from frontend
  README.md
  e2eTesting/httpinessFiles/httpE2ETestCollection.json
  habit-storage/lambda/deleteHabit.mjs
  habit-storage/lambda/editHabit.mjs
  habit-storage/lib/habit-storage-stack.ts
  habit-storage/lib/habitStorage.ts
  habit-storage/test/deleteHabit.test.mjs
  habit-storage/test/editHabit.test.mjs
Labels: enhancement

#53 48 feature update storinghabitdatalambda to store incomming habit event data in habiteventtable
  firmwareSimulator/certificates/firmwareSimulatorThing-Policy
  firmwareSimulator/config_pb2.py
  firmwareSimulator/habitTracker.py
  firmwareSimulator/main.py
  firmwareSimulator/protocol_buffers_messages/config.proto
  habit-event-storage/lambda/storingHabitDataLambda.mjs
  habit-event-storage/lib/habit-event-storage-stack.ts
  habit-event-storage/lib/habitEventStorage.ts
  package-lock.json
  package.json
Labels: enhancement

#61 [#60] fix: Make cors work
  habit-storage/lib/habit-storage-stack.ts
Labels: bug

#62 [#59]bug: Update protocolBuffersToJSONRule
  firmwareSimulator/.gitignore
  firmwareSimulator/Scripts/Activate.ps1
  firmwareSimulator/Scripts/activate
  firmwareSimulator/Scripts/activate.bat
  firmwareSimulator/Scripts/deactivate.bat
  firmwareSimulator/Scripts/pip.exe
  firmwareSimulator/Scripts/pip3.12.exe
  firmwareSimulator/Scripts/pip3.exe
  firmwareSimulator/Scripts/python.exe
  firmwareSimulator/Scripts/pythonw.exe
  firmwareSimulator/certificates/firmwareSimulatorThing-Policy
  firmwareSimulator/main.py
  habit-event-storage/lib/habit-event-storage-stack.ts
  package-lock.json
  package.json
Labels: bug

#66 27 feature implement backend resources for user registration and user login
  README.md
  e2eTesting/httpinessFiles/HabitEventStorageHTTPe2e.json
  e2eTesting/httpinessFiles/authentificatione2e.json
  e2eTesting/httpinessFiles/httpE2ETestCollection.json
  habit-event-storage/lambda/getHabitEventFromUser.mjs
  habit-event-storage/lambda/getHabitEvents.mjs
  habit-event-storage/lambda/storingHabitDataLambda.mjs
  habit-event-storage/lambda/updateHabitEvent.mjs
  habit-event-storage/lib/habitEventStorage.ts
  habit-event-storage/lib/httpApi.ts
  habit-event-storage/test/getHabitEventFromUser.test.mjs
  habit-event-storage/test/getHabitEvents.test.mjs
  habit-storage/lambda/createHabit.mjs
  habit-storage/lambda/deleteHabit.mjs
  habit-storage/lambda/editHabit.mjs
  habit-storage/lambda/getHabits.mjs
  habit-storage/lambda/getHabitsWithSide.mjs
  habit-storage/lib/habit-storage-stack.ts
  habit-storage/lib/habitStorage.ts
  user-pool/.eslintrc.json
  user-pool/.gitignore
  user-pool/.npmignore
  user-pool/.prettierrc
  user-pool/README.md
  user-pool/bin/user-pool.ts
  user-pool/cdk.context.json
  user-pool/cdk.json
  user-pool/jest.config.js
  user-pool/lambda/login.mjs
  user-pool/lambda/signup.mjs
  user-pool/lambda/verifyEmail.mjs
  user-pool/lib/user-pool-stack.ts
  user-pool/package-lock.json
  user-pool/package.json
  user-pool/test/login.test.mjs
  user-pool/test/signup.test.mjs
  user-pool/test/user-pool.test.ts
  user-pool/test/verifyEmail.test.mjs
  user-pool/tsconfig.json
Labels: enhancement

#68 64 feature implement setup for firmware simulator
  firmwareSimulator/certificates/firmwareSimulatorThing-Policy
  firmwareSimulator/main.py
  firmwareSimulator/src/FirmwareSimulator.py
  firmwareSimulator/src/__init__.py
  firmwareSimulator/src/config.py
  firmwareSimulator/src/config_pb2.py
  firmwareSimulator/src/fromFirmwareToBackend_pb2.py
  firmwareSimulator/src/main.py
  firmwareSimulator/src/setup.py
Labels: enhancement

#70 67 feature create api for storing and getting habit goals
  README.md
  e2eTesting/httpinessFiles/HabitEventStorageHTTPe2e.json
  e2eTesting/httpinessFiles/httpE2ETestCollection.json
  habit-event-storage/lambda/getHabitGoal.mjs
  habit-event-storage/lambda/setHabitGoal.mjs
  habit-event-storage/lambda/storingHabitDataLambda.mjs
  habit-event-storage/lib/habit-event-storage-stack.ts
  habit-event-storage/lib/habitEventStorage.ts
  habit-event-storage/lib/httpApi.ts
  habit-event-storage/test/getHabitEventFromUser.test.mjs
  habit-event-storage/test/getHabitGoal.test.mjs
  habit-event-storage/test/setHabitGoal.test.mjs
  habit-storage/lambda/createHabit.mjs
  habit-storage/lambda/deleteHabit.mjs
  habit-storage/lambda/editHabit.mjs
  habit-storage/lambda/getHabitsWithSide.mjs
  habit-storage/test/createHabit.test.mjs
  habit-storage/test/getHabitsWithSide.test.mjs
  user-pool/lambda/login.mjs
Labels: documentation, enhancement

#76 [75]fix: Update proto, desc and zip file in s3 bucket
  habit-event-storage/proto-files/fromFirmwareToBackend.desc
  habit-event-storage/proto-files/fromFirmwareToBackend.proto
  habit-event-storage/proto-files/fromFirmwareToBackend.zip
Labels: bug

#77 74 bug fix edithabit
  habit-event-storage/lib/httpApi.ts
  habit-storage/lambda/editHabit.mjs
  habit-storage/test/editHabit.test.mjs
Labels: bug

#78 69 feature update how firmwaresimulator receives updates from aws
  firmwareSimulator/certificates/firmwareSimulatorThing-Policy
  firmwareSimulator/dodecahedron/dodecahedron.json
  firmwareSimulator/protocol_buffers_messages/config.proto
  firmwareSimulator/protocol_buffers_messages/fromFirmwareToBackend.desc
  firmwareSimulator/protocol_buffers_messages/fromFirmwareToBackend.proto
  firmwareSimulator/src/FirmwareSimulator.py
  firmwareSimulator/src/config.py
  firmwareSimulator/src/config_pb2.py
  firmwareSimulator/src/fromFirmwareToBackend_pb2.py
  firmwareSimulator/src/main.py
  firmwareSimulator/src/setup.py
Labels: enhancement

#80 #79 feature update firmwaresimulator documentation
  firmwareSimulator/README.md
  firmwareSimulator/certificates/.gitkeep
  firmwareSimulator/src/FirmwareSimulator.py
  firmwareSimulator/src/__init__.py
  firmwareSimulator/src/main.py
  firmwareSimulator/src/setup.py
  habit-event-storage/lambda/storingHabitDataLambda.mjs
  habit-event-storage/lib/habit-event-storage-stack.ts
Labels: documentation
